# Generated by Django 5.1 on 2024-09-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
